config/routes.rb
Rails.application.routes.draw do

  root 'users#welcome'

  resources :loans

  resources :users do
    resources :loans
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/models/loan.rb
class Loan < ActiveRecord::Base
  belongs_to :user

  # validates :title, presence: true
  # validates :body, presence: true

  def self.search(search)
    where("title ILIKE ? OR category ILIKE ?", "%#{search}%", "%#{search}%")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :loans
  has_secure_password

  validates :user_name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
        # or =
        # if current_user is already a thing, then don't look for it
        # that way you only find the current_user one time
        # if current_user is not true, then do the command User.find
    end
    helper_method(:current_user)
    #this calls the helper method on user when the action loads

  # You cannot view any show page unless you are logged in
    def authorize # we can call it anything
      redirect_to '/login' unless current_user # if there is a current user then it will never redirect
    end

end # end of class

app/controllers/loans_controller.rb
class LoansController < ApplicationController

  before_action :authorize

  def index
    @loans = Loan.all

    if params[:search]
      @loans = Loan.search(params[:search]).order("created_at DESC")
    else
      @loans = Loan.all.order('created_at DESC')
    end
  end


  def show
    @loan = Loan.find(params[:id])
  end

  def new
    @loan = Loan.new
    # id = session[:user_id]
    # @user = User.find(id)
  end

  def create
    loan = Loan.create(loan_params)
    loan.user_id = current_user.id
    if loan.save
      redirect_to '/loans'
    else
      redirect_to '/loans/new'
    end
  end

  def edit
    @loan = Loan.find(params[:id])
  end

  def update
    loan = Loan.find(params[:id])
    if loan.update(loan_params)
      redirect_to '/loans'
    else
      redirect_to '/loans/edit'
    end
  end

  def destroy
    loan = Loan.find(params[:id])
    loan.destroy
    redirect_to '/loans'
  end

  # TRIED TO IMPLEMENT SEARCH FORM BUT DID NOT WORK
  # def sort
  #   @sorted_loans = Loan.all
  # end

  private

  def loan_params
    params.require(:loan).permit(
      :title,
      :loan_amount,
      :loan_description,
      :location,
      :category,
      :start_date,
      :term,
      :interest_rate
    )
  end
end # end of class

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new #loging form
  end

  def create
    # user puts in email and password
    # create a new session if they match
    user = User.find_by_user_name(params[:user_name]) # do not worry about strong params because we are not putting it into database
    # binding.pry
    if user && user.authenticate(params[:password]) #authenticate is a bcrypt method
      session[:user_id] = user.id
      redirect_to("/")

    else
      redirect_to("/login")
    end
  end

  def destroy # logout
    session[:user_id] = nil
    redirect_to('/')
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize, except: [:welcome, :new, :create]

  def welcome
    @users = User.all
  end

  def index
    # @test = "Hello world"
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      # redirect_to('/')
      redirect_to @user
    else
      # redirect_to 'users/new'
      render 'new'
    end
  end

  def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to @user
      else
        render 'edit'
      end
    end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(
    :user_name,
    :company_name,
    :user_description,
    :town,
    :borrower,
    :password,
    :password_confirmation
    )
  end

end   # end of class

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= stylesheet_link_tag("style.css") %>
<html>
<head>
  <title>FundingMatch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class = "top_header">
    <h1> Lending Pal - Match Lending Site </h1>
  </div>

<div class = "log_bar">
    <% if current_user %>
        Signed in as <%= current_user.user_name %> | <%= link_to "logout", "/logout" %>
    <% else %>
      <%= link_to "Login", "/login" %> | <%= link_to "Sign Up", new_user_path%>
    <% end %>
</div>

<div class = "main_content" >

<%= yield %>

</div>

</body>
</html>

app/views/loans/_form.html.erb
<%= form_for @loan do |f| %>

<% if @loan.errors.any? %>
  <div id="error message">
    <h2>
      <%= pluralize(@loan.errors.count,"error") %>
      this Loan information from being saved:
    </h2>
    <ul>
      <% @loan.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
      <% end %>
    </ul>
  </div>
  <% end %>
<p>
  <%= f.label :title%><br>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :loan_amount%><br>
  <%= f.text_field :loan_amount %>
</p>

<p>
  <%= f.label :category%><br>
  <%= f.text_field :category%>
</p>

<p>
  <%= f.label :loan_description%><br>
  <%= f.text_area :loan_description, size: "60x12" %>
</p>

<p>
  <%= f.label :location%><br>
  <%= f.text_field :location%>
</p>

<p>
  <%= f.label :start_date%><br>
  <%= f.text_field :start_date%>
</p>

<p>
  <%= f.label :term%><br>
  <%= f.text_field :term%>
</p>

<p>
  <%= f.label :interest_rate%><br>
  <%= f.text_field :interest_rate%>
</p

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/loans/edit.html.erb
<h1> Editing Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', loans_path %>

app/views/loans/index.html.erb
<%= stylesheet_link_tag("style.css") %>

<div class ='navigation_bar' >
  <%= link_to "Home Page", root_path%> ||
  <%= link_to "User Profiles", users_path%>  ||
  <%= link_to "Post New Loan", new_loan_path %> ||
  <%= link_to "Display All Loans", loans_path %> ||

</div>

<%= form_tag(loans_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], size: 50, placeholder: "Search by Category or Title" %>
<%= submit_tag "Search" %>
<% end %>

<h2>Loans available for funding </h2>

  <% @loans.each do |loan| %>
  <div class="loans">
    <h3> <%= link_to "Loan Profile Details", loan_path(loan) %> </h3>

    <p> <strong> Person name: </strong> <%= loan.user.user_name %> </p>
    <p> <strong> Title: </strong> <%= loan.title %> </p>
    <p> <strong> Category: </strong> <%= loan.category %> </p>
    <p> <strong> Loan Amount: </strong> <%= loan.loan_amount %> </p>
    <p> <strong> Location: </strong> <%=loan.location %> </p>
  </div>
  <% end %>

app/views/loans/new.html.erb
<%= form_for @loan, url: "/loans" do |f| %>

<table>
    <tr><td> Title: </td> <td> <%= f.text_field :title %> </td></tr>
    <tr><td> Amount: </td> <td> <%= f.text_field :loan_amount %> </td></tr>

    <tr><td> Description </td> <td> <%= f.text_area :loan_description %> </td></tr>
    <tr><td> Location: </td> <td> <%= f.text_field :location %> </td></tr>
    <tr><td> Category: </td> <td> <%= f.text_field :category %> </td></tr>
    <tr><td> Start Date: </td> <td> <%= f.text_field :start_date %> </td></tr>
    <tr><td> Term: </td> <td> <%= f.text_field :term %> </td></tr>
    <tr><td> Interest Rate: </td> <td> <%= f.text_field :interest_rate %> </td></tr>
</table>

  <%= f.submit "Submit New Loan Information" %>

<% end %>

app/views/loans/show.html.erb
<div class = 'loan_profile'>

  <h2> Loan Profile Details </h2>
  <p>
    <strong>Loan ID:</strong>
    <%= @loan.id %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= @loan.title %>
  </p>

  <p>
    <strong>Caterory</strong>
    <%= @loan.category %>
  </p>

  <p>
    <strong>Loan Amount:</strong>
    <%= @loan.loan_amount %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @loan.loan_description %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= @loan.location %>
  </p>

  <p>
    <strong>Start Date</strong>
    <%= @loan.start_date %>
  </p>

  <p>
    <strong>Interest Rate</strong>
    <%= @loan.interest_rate %>
  </p>

</div>

<%= link_to 'Edit', edit_loan_path(@loan) %> ||
<%= link_to 'Back to Loan Index', loans_path %>
<%= link_to 'Delete', loan_path(@loan),
    method: :delete,
    data: { confirm: 'Are you sure? Delete is permanent.  Please confirm.'} %>

app/views/loans/sort.html.erb
PENDING

<h1>Loans classified with category <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

<% if @user.errors.any? %>
  <div id="error message">
    <h2>
      <%= pluralize(@user.errors.count,"error") %>
      this User Information from being saved:
    </h2>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
      <% end %>
    </ul>
  </div>
  <% end %>

<p>
  <%= f.label :user_name%><br>
  <%= f.text_field :user_name %>
</p>

<p>
  <%= f.label :company_name%><br>
  <%= f.text_field :company_name %>
</p>

<p>
  <%= f.label :user_description%><br>
  <%= f.text_area :user_description, size: "60x12" %>
</p>

<p>
  <%= f.label :town%><br>
  <%= f.text_field :town %>
</p>

<p>
  <%= f.label :borrower_type%><br>
  <%= f.text_field :borrower%>
</p>

<p>
  <%= f.label :password%><br>
  <%= f.text_field :password%>
</p>

<p>
  <%= f.label :password_confirmation%><br>
  <%= f.text_field :password_confirmation%>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/users/_loan.html.erb
<div class = "loans">
  <h3> <%= link_to "Loan Profile Details", loan_path(loan) %> </h3>

  <p> <%= loan.title%> </p>
  <p> <strong> Category: </strong> <%= loan.category %> </p>
  <p> <strong> Loan Amount: </strong> <%= loan.loan_amount %> </p>
  <p> <strong> Location: </strong> <%=loan.location %> </p>
</div>

app/views/users/edit.html.erb
<h1> Editing Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<%= stylesheet_link_tag("style.css") %>

<div class ='navigation_bar' >
  <%= link_to "Loan Profiles", loans_path%>  ||
  <%= link_to "Home Page", root_path%>
</div>

<h2> Index of User Profiles </h2>

    <% @users.each do |user| %>
    <div class="user_profile">
    <h3> <%= link_to "Profile of: #{user.user_name}", user_path(user) %> </h3>
    <p> Company: <%= user.company_name %> </p>
    <p> Town: <%= user.town %> <p>
    </div>
    <% end %>

app/views/users/new.html.erb
<h1> Sign Up </h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="user_profile">
  <h3> Profile of <%= @user.user_name %> </h3>
  <p>
    <strong>User Type:</strong>
    <% if @user.borrower == true %>
      <%= "Borrower" %>
    <% else %>
      <%= "Lender"%>
    <%end%>
  </p>

  <p>
    <strong>Person Name:</strong>
    <%= @user.user_name %>
  </p>

  <p>
    <strong>Company Name:</strong>
    <%= @user.company_name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @user.user_description %>
  </p>

  <p>
    <strong>Town:</strong>
    <%= @user.town %>
  </p>

</div>


<h3> (<%= @user.loans.size %>) Loans posted by <%= @user.user_name %> from <%= @user.company_name %></h3>


<%= render partial: 'users/loan', collection: @user.loans %>


<%= link_to 'Edit', edit_user_path(@user) %> ||
<%= link_to 'Back to Users Index', users_path %> ||
<%= link_to 'Delete', user_path(@user),
    method: :delete,
    data: { confirm: 'Are you sure? Delete is permanent.  Please confirm.'} %> ||
<%= link_to "Post New Loan", new_user_loan_path(@user) %>

app/views/users/welcome.html.erb
<h2> Welcome to the Funding Match site</h2>
<h3> The solution to matching borrowers with lenders </h3>
<!-- <h3> View the profiles of users </h3> -->
<h3> <%= link_to "View Users' Profiles", "/users" %> </h3>
<h3> <%= link_to "View Loans Available for Funding", "/loans" %> </h3>